version: '3.7'

services:
  postgresdb:
    image: postgres:alpine3.14
    container_name: postgresdb
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "54320:5432"
    networks:
      - postgres_network
    volumes:
      - /data:/var/lib/postgresql

volumes:
  postgres_data:
    external: false
      
networks:
  postgres_network:
    driver: bridge
      